
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package lexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 53;
  public static final int OPERADOR_Y = 22;
  public static final int ENTRE_IGUAL = 11;
  public static final int PARENTESIS_IZQUIERDO = 16;
  public static final int PASAR = 52;
  public static final int PUNTO_Y_COMA = 14;
  public static final int IMPRIMIR = 43;
  public static final int OPERADOR_O = 23;
  public static final int SI = 35;
  public static final int FUNCION = 39;
  public static final int DIFERENTE = 3;
  public static final int PAUSA = 48;
  public static final int RESTA = 30;
  public static final int DESDE = 45;
  public static final int DOS_PUNTOS = 15;
  public static final int CORCHETE_DER = 19;
  public static final int CONTINUA = 50;
  public static final int HASTA = 38;
  public static final int DEFINE = 51;
  public static final int IDENTIFICADOR = 55;
  public static final int LLAVE_IZQ = 20;
  public static final int IGUAL = 2;
  public static final int SINO = 34;
  public static final int MIENTRAS = 36;
  public static final int COMO = 47;
  public static final int SUMA = 29;
  public static final int MAS_IGUAL = 8;
  public static final int RETORNO = 40;
  public static final int EOF = 0;
  public static final int PARENTESIS_DER = 17;
  public static final int CLASE = 49;
  public static final int error = 1;
  public static final int NULO = 46;
  public static final int COMA = 13;
  public static final int MODULO = 33;
  public static final int MENOR = 7;
  public static final int ERROR = 56;
  public static final int ASIGNACION = 12;
  public static final int REAL = 54;
  public static final int MAYOR = 6;
  public static final int OPERADOR_NOES = 27;
  public static final int OPERADOR_NOEN = 26;
  public static final int LLAVE_DER = 21;
  public static final int CORCHETE_IZQ = 18;
  public static final int MAYOR_IGUAL = 4;
  public static final int POR_IGUAL = 10;
  public static final int FALSO = 42;
  public static final int OPERADOR_ES = 28;
  public static final int LEER = 44;
  public static final int PARA = 37;
  public static final int OPERADOR_EN = 25;
  public static final int VERDADERO = 41;
  public static final int MENOR_IGUAL = 5;
  public static final int MENOS_IGUAL = 9;
  public static final int DIVISION = 32;
  public static final int OPERADOR_NO = 24;
  public static final int MULTIPLICACION = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IGUAL",
  "DIFERENTE",
  "MAYOR_IGUAL",
  "MENOR_IGUAL",
  "MAYOR",
  "MENOR",
  "MAS_IGUAL",
  "MENOS_IGUAL",
  "POR_IGUAL",
  "ENTRE_IGUAL",
  "ASIGNACION",
  "COMA",
  "PUNTO_Y_COMA",
  "DOS_PUNTOS",
  "PARENTESIS_IZQUIERDO",
  "PARENTESIS_DER",
  "CORCHETE_IZQ",
  "CORCHETE_DER",
  "LLAVE_IZQ",
  "LLAVE_DER",
  "OPERADOR_Y",
  "OPERADOR_O",
  "OPERADOR_NO",
  "OPERADOR_EN",
  "OPERADOR_NOEN",
  "OPERADOR_NOES",
  "OPERADOR_ES",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "MODULO",
  "SINO",
  "SI",
  "MIENTRAS",
  "PARA",
  "HASTA",
  "FUNCION",
  "RETORNO",
  "VERDADERO",
  "FALSO",
  "IMPRIMIR",
  "LEER",
  "DESDE",
  "NULO",
  "COMO",
  "PAUSA",
  "CLASE",
  "CONTINUA",
  "DEFINE",
  "PASAR",
  "NUMERO",
  "REAL",
  "IDENTIFICADOR",
  "ERROR"
  };
}

