
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Lexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TOKEN_DESDE = 17;
  public static final int ERROR = 3;
  public static final int TOKEN_PARA = 9;
  public static final int TOKEN_MIENTRAS = 8;
  public static final int TOKEN_RETORNO = 12;
  public static final int TOKEN_SI = 6;
  public static final int TOKEN_ENTERO = 18;
  public static final int TOKEN_SINO = 7;
  public static final int TOKEN_HASTA = 10;
  public static final int TOKEN_FUNCION = 11;
  public static final int EOF = 0;
  public static final int TOKER_LEER = 16;
  public static final int COMILLA = 2;
  public static final int TOKEN_BOOL = 4;
  public static final int error = 1;
  public static final int TOKEN_IMPRIMIR = 15;
  public static final int TOKEN_CADENA = 5;
  public static final int TOKEN_FALSO = 14;
  public static final int TOKEN_REAL = 19;
  public static final int TOKEN_VERDADERO = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMILLA",
  "ERROR",
  "TOKEN_BOOL",
  "TOKEN_CADENA",
  "TOKEN_SI",
  "TOKEN_SINO",
  "TOKEN_MIENTRAS",
  "TOKEN_PARA",
  "TOKEN_HASTA",
  "TOKEN_FUNCION",
  "TOKEN_RETORNO",
  "TOKEN_VERDADERO",
  "TOKEN_FALSO",
  "TOKEN_IMPRIMIR",
  "TOKER_LEER",
  "TOKEN_DESDE",
  "TOKEN_ENTERO",
  "TOKEN_REAL"
  };
}

